"""Paper identity: stable identifiers, and the joins that used to be fuzzy.

The problem this solves
-----------------------
Every join in this pipeline used to be a title-string comparison, and titles are
not stable across sources: BibTeX braces capitalization (`{B}aby{LM}`), Scholar
lowercases subtitles, and the author's own table is typed by hand. So the
citation join silently mismatched -- two BabyLM papers holding 490 citations
between them both reported 0, because `difflib` compared raw strings and then
one match overwrote the other with no warning.

The design
----------
Sources hand out stable identifiers, and we write them down the first time we
see them, so a fuzzy match happens at most once per paper ever:

  * Google Scholar    `citation_for_view=USER:PUBID`, scraped from the profile row
  * Semantic Scholar  `externalIds` -> {ArXiv, DOI, ACL, DBLP, CorpusId} together,
                      which is the crosswalk when ACL knows no arXiv ID and
                      vice versa
  * ACL / arXiv / DOI as they appear in the bibliography

Ownership is split deliberately. The human-edited table owns judgements (venue,
tags, whether it counts as a paper); `identity.json` owns machine-harvested IDs.
One writer each, so a refresh never fights a hand edit and neither produces
merge conflicts in the other's file.

Match tiers, most trusted first -- `MATCH_EXACT_ID`, `MATCH_NORMALIZED`,
`MATCH_FUZZY`. Anything resolved below `MATCH_EXACT_ID` is reported as needing
confirmation, and anything ambiguous is reported rather than guessed.
"""

import difflib
import json
import os
import re

from bib_utils import extract_field, normalize_text, parse_bibtex

FILE_DIR = os.path.dirname(os.path.abspath(__file__))
IDENTITY_PATH = os.path.join(FILE_DIR, "identity.json")

# Match tiers, in descending trust. Only MATCH_EXACT_ID needs no human review.
MATCH_EXACT_ID = "exact-id"
MATCH_NORMALIZED = "normalized-title"
MATCH_FUZZY = "fuzzy-title"

# Ambiguity, reported rather than resolved.
MATCH_TOO_CLOSE = "too-close-to-call"

# Fuzzy thresholds. difflib.get_close_matches' 0.6 default was far too loose --
# it happily matched different papers in the same series. But raising the bar
# alone loses real renames: this table says "Will it Blend? Weak and Manual
# Labeled Data..." where Scholar says "Will it blend? blending weak and strong
# labeled data...", which is the same paper at 0.84. So there are two bars:
# accept silently above FUZZY_CUTOFF, accept but flag for confirmation above
# FUZZY_REVIEW_CUTOFF, reject below it.
FUZZY_CUTOFF = 0.90
FUZZY_REVIEW_CUTOFF = 0.75

# A fuzzy winner must beat the runner-up by this margin. Without it, the two
# "Findings of the {second,third} BabyLM Challenge" papers are each other's
# best non-exact match and either could win.
FUZZY_MARGIN = 0.05

# Fuzzy matching needs this many normalized characters to mean anything. Exact
# normalized matching is *not* gated on length -- a table row titled
# "TextArena" normalizes to 9 characters and must still match Scholar's
# "Textarena" exactly.
MIN_FUZZY_CHARS = 20

ID_FIELDS = ("scholar_id", "arxiv", "doi", "acl", "s2", "dblp")


def normalize_title(title):
    """Normalize a title for comparison across sources.

    Strips everything that differs between sources by convention rather than by
    meaning: case, punctuation, whitespace, and BibTeX's capitalization braces.
    """
    return normalize_text(title)


def title_stem(title):
    """Normalize, dropping a short prefix before a colon.

    Scholar renders series and project prefixes inconsistently ("Project
    Debater: An Autonomous Debating System" vs "An autonomous debating system"),
    so the longer side of a colon is the more reliable comparison key. Only used
    as a fallback below normalized matching, never for an exact claim.
    """
    t = (title or "").strip()
    if ":" in t:
        t = max((p.strip() for p in t.split(":", 1)), key=len)
    return normalize_text(t)


class IdentityStore:
    """Machine-harvested identifiers per paper, persisted to identity.json.

    Keyed by BibTeX key. `titles` records every spelling of a title we have seen
    for the paper, which is what lets a renamed title still resolve; `rekey`
    moves a record when a key changes.
    """

    def __init__(self, records=None):
        self.records = records or {}

    # ── persistence ──────────────────────────────────────────────────────────

    @classmethod
    def load(cls, path=IDENTITY_PATH):
        try:
            with open(path) as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError):
            return cls()
        return cls(data.get("records", {}))

    def save(self, path=IDENTITY_PATH):
        """Persist atomically, sorted, so the file diffs cleanly in git."""
        tmp = path + ".tmp"
        payload = {
            "_comment": "Machine-harvested paper identifiers. Regenerated by "
                        "update.py; safe to delete (it will be rebuilt, at the "
                        "cost of re-resolving). Hand edits belong in the "
                        "publications table, not here.",
            "records": {k: self.records[k] for k in sorted(self.records)},
        }
        with open(tmp, "w") as f:
            json.dump(payload, f, indent=2, sort_keys=True)
            f.write("\n")
        os.replace(tmp, path)

    # ── mutation ─────────────────────────────────────────────────────────────

    def record(self, key, title=None, **ids):
        """Merge identifiers (and a seen title spelling) into a paper's record.

        Never overwrites a stored identifier with a different value -- a
        conflict means two papers were conflated, which is reported by
        `conflicts()` rather than silently resolved.
        """
        rec = self.records.setdefault(key, {})
        for field, value in ids.items():
            if field not in ID_FIELDS or not value:
                continue
            value = str(value).strip()
            existing = rec.get(field)
            if existing and existing != value:
                rec.setdefault("_conflicts", {}).setdefault(field, [])
                if value not in rec["_conflicts"][field]:
                    rec["_conflicts"][field].append(value)
                continue
            rec[field] = value
        if title:
            titles = rec.setdefault("titles", [])
            norm = normalize_title(title)
            if norm and norm not in titles:
                titles.append(norm)
        return rec

    def rekey(self, old_key, new_key):
        """Move a synthetic-key record onto its real BibTeX key once assigned."""
        if old_key == new_key or old_key not in self.records:
            return
        merged = self.records.pop(old_key)
        target = self.records.setdefault(new_key, {})
        for field, value in merged.items():
            if field == "titles":
                seen = target.setdefault("titles", [])
                seen.extend(t for t in value if t not in seen)
            else:
                target.setdefault(field, value)

    def conflicts(self):
        """Return [(key, field, [values])] where a source disagreed with us."""
        out = []
        for key, rec in sorted(self.records.items()):
            for field, values in (rec.get("_conflicts") or {}).items():
                out.append((key, field, [rec.get(field)] + list(values)))
        return out

    # ── lookup ───────────────────────────────────────────────────────────────

    def index(self, field):
        """Return {identifier_value: paper_key} for one ID field.

        First key wins, deterministically by sort order. A value claimed by more
        than one paper is a data problem, not something to resolve here -- see
        `shared_identifiers()`.
        """
        out = {}
        for key in sorted(self.records):
            value = (self.records[key] or {}).get(field)
            if value and value not in out:
                out[value] = key
        return out

    def shared_identifiers(self):
        """Return [(field, value, [keys])] where one identifier names two papers.

        Two bib keys carrying the same Scholar ID or DOI means the same paper is
        recorded twice -- usually a duplicate table row. Silently collapsing them
        (which `index` has to do) would hide it, so it is surfaced instead.
        """
        out = []
        for field in ID_FIELDS:
            owners = {}
            for key in sorted(self.records):
                value = (self.records[key] or {}).get(field)
                if value:
                    owners.setdefault(normalize_identifier(field, value), []).append(key)
            out.extend((field, value, keys)
                       for value, keys in sorted(owners.items()) if len(keys) > 1)
        return out

    def title_index(self):
        """Return {normalized_title: paper_key} over every recorded spelling."""
        out = {}
        for key, rec in self.records.items():
            for norm in rec.get("titles", []):
                out.setdefault(norm, key)
        return out


# ── the citation join ────────────────────────────────────────────────────────

class JoinResult:
    """Outcome of joining an external source onto the publications table.

    `matched` maps source-table row name -> value. `needs_review` and
    `unmatched` are what the worklist reports; nothing here is silently dropped.
    """

    def __init__(self):
        self.matched = {}
        self.method = {}
        # row_name -> the incoming row that won it. Needed to bind identifiers:
        # for a fuzzy match the two titles differ by definition, so the table
        # name alone cannot find its way back to the source record.
        self.source = {}
        self.needs_review = []   # (row_name, incoming_title, tier, score)
        # Several records for one paper, summed. Informational, not an action.
        self.aggregated = []     # (row_name, [(title, tier, score), ...], total)
        # Several records that are NOT the same paper landing on one row. Real.
        self.ambiguous = []      # (row_name, [(title, tier, score), ...], total)
        # One record that could equally be two different rows. Reported, never guessed.
        self.too_close = []      # (incoming_title, value, score)
        self.unmatched = []      # (incoming_title, value)

    def tier_counts(self):
        counts = {}
        for tier in self.method.values():
            counts[tier] = counts.get(tier, 0) + 1
        return counts


def _candidate_key(row_names_by_norm, stems_by_norm, title):
    """Resolve one incoming title to a row name.

    Returns (row_name, tier, score). `tier` is None when nothing matched, and
    MATCH_TOO_CLOSE (with row_name None) when two rows are indistinguishable --
    the caller reports that rather than picking one.
    """
    norm = normalize_title(title)
    if not norm:
        return None, None, 0.0

    # Exact on the normalized title. Length-independent: this is an identity
    # claim, not a similarity guess.
    if norm in row_names_by_norm:
        return row_names_by_norm[norm], MATCH_NORMALIZED, 1.0

    # Exact on the longer side of a colon, for series/project prefixes that one
    # source includes and the other drops.
    stem = title_stem(title)
    if stem and stem in stems_by_norm:
        return stems_by_norm[stem], MATCH_NORMALIZED, 1.0

    if len(norm) < MIN_FUZZY_CHARS:
        return None, None, 0.0

    # Sorted by (score, name) so ties break deterministically rather than on
    # dict iteration order.
    scored = sorted(
        ((difflib.SequenceMatcher(None, norm, cand_norm).ratio(), name)
         for cand_norm, name in row_names_by_norm.items()),
        reverse=True,
    )
    if not scored:
        return None, None, 0.0
    best_score, best_name = scored[0]
    runner_up = scored[1][0] if len(scored) > 1 else 0.0

    if best_score < FUZZY_REVIEW_CUTOFF:
        return None, None, best_score
    if best_score - runner_up < FUZZY_MARGIN:
        return None, MATCH_TOO_CLOSE, best_score
    return best_name, MATCH_FUZZY, best_score


def join_citations(citation_rows, row_names, store=None):
    """Join scraped citation counts onto publications-table row names.

    `citation_rows` are dicts with at least `title` and `citations`, optionally
    `scholar_id`. `row_names` are the table's paper names.

    Tiers are tried in descending trust and a stronger tier always wins, so the
    result does not depend on input order -- unlike the previous implementation,
    where the last writer won and one BabyLM paper's count overwrote another's.
    Two incoming rows landing on one table row at the same tier is reported as
    ambiguous instead of being resolved arbitrarily.
    """
    store = store or IdentityStore()
    result = JoinResult()

    # Sorted, not set-ordered: when two table rows are duplicates of each other
    # only one can win, and which one must not depend on PYTHONHASHSEED.
    row_names = sorted({str(n).strip() for n in row_names if str(n).strip()})
    names_by_norm, stems_by_norm = _title_indexes(row_names)

    # scholar_id -> the table row it was previously bound to
    scholar_to_key = store.index("scholar_id")
    key_to_name = {}
    title_idx = store.title_index()
    for norm, name in names_by_norm.items():
        key = title_idx.get(norm)
        if key:
            key_to_name[key] = name

    tier_rank = {MATCH_EXACT_ID: 3, MATCH_NORMALIZED: 2, MATCH_FUZZY: 1}
    claims = {}  # row_name -> [(tier, score, incoming_row), ...]

    for row in citation_rows:
        title = str(row.get("title") or "").strip()
        value = row.get("citations")
        scholar_id = str(row.get("scholar_id") or "").strip()

        name = tier = None
        score = 0.0
        if scholar_id and scholar_id in scholar_to_key:
            name = key_to_name.get(scholar_to_key[scholar_id])
            if name:
                tier, score = MATCH_EXACT_ID, 1.0
        if name is None:
            name, tier, score = _candidate_key(names_by_norm, stems_by_norm, title)

        if name is None:
            if tier == MATCH_TOO_CLOSE:
                result.too_close.append((title, value, score))
            result.unmatched.append((title, value))
            continue

        claims.setdefault(name, []).append((tier, score, row))

    for name, matches in claims.items():
        # Best tier and its row represent the paper; the count is the *total*
        # across every record that matched.
        matches.sort(key=lambda m: (tier_rank[m[0]], m[1]), reverse=True)
        tier, score, best_row = matches[0]

        titles = [str(m[2].get("title") or "") for m in matches]
        # Are these records all the same paper? Only then may their counts be
        # added. Two *different* papers landing on one row is a data problem, and
        # summing them would invent a number.
        same_paper = all(
            difflib.SequenceMatcher(
                None, normalize_title(t), normalize_title(titles[0])
            ).ratio() >= FUZZY_REVIEW_CUTOFF
            for t in titles[1:])

        if same_paper:
            # Scholar splits a paper across records when it has not merged the
            # preprint with the published version. Each record counts a
            # different set of citing papers, so the paper's total is their sum,
            # which is what Scholar itself shows once the versions are merged.
            present = [m[2].get("citations") for m in matches
                       if m[2].get("citations") is not None]
            # All-None stays None: "no count reported" is not a count of zero.
            result.matched[name] = sum(present) if present else None
        else:
            # Fall back to the most-trusted single record rather than inventing
            # a total across papers that are not the same.
            result.matched[name] = best_row.get("citations")

        result.method[name] = tier
        result.source[name] = best_row

        if len(matches) > 1:
            entry = (name, [(titles[i], m[0], m[1]) for i, m in enumerate(matches)],
                     result.matched[name])
            (result.aggregated if same_paper else result.ambiguous).append(entry)

        if tier == MATCH_FUZZY:
            result.needs_review.append((name, str(best_row.get("title") or ""),
                                        tier, score))

    return result


def _title_indexes(known_titles):
    """Build the normalized and colon-stem lookups `_candidate_key` needs."""
    names_by_norm, stems_by_norm = {}, {}
    for name in sorted({str(t).strip() for t in known_titles if str(t).strip()}):
        names_by_norm.setdefault(normalize_title(name), name)
        stem = title_stem(name)
        if stem:
            stems_by_norm.setdefault(stem, name)
    return names_by_norm, stems_by_norm


def classify_title(incoming, known_titles):
    """Is `incoming` one of `known_titles`? Returns (matched, tier, score).

    Deliberately the *same* decision as the citation join -- it calls
    `_candidate_key`, the join's own matcher.

    Using a stricter bar here instead was a bug: the join accepted the retitled
    "Will it blend? blending weak and strong..." as the table's "Will it Blend?
    Weak and Manual..." at 0.88, while step 2 called it new and appended a row.
    So every fuzzy-matched paper gained a duplicate row on every single run,
    each of which then made the citation join ambiguous. Five such rows appeared
    the first time this ran.

    One question ("are these the same paper?") gets one answer. Because the bar
    is permissive, every non-exact verdict is reported by the caller rather than
    applied silently -- a wrongly-skipped new paper shows up in a report, whereas
    a wrongly-added duplicate quietly corrupts the CV and the citation counts.
    """
    names_by_norm, stems_by_norm = _title_indexes(known_titles)
    return _candidate_key(names_by_norm, stems_by_norm, incoming)


def titles_match(incoming, known):
    """True if two titles are the same paper. Pairwise form of `classify_title`."""
    matched, _tier, _score = classify_title(incoming, [known])
    return matched is not None


def duplicate_groups_by_identifier(store, keys_in_use=None):
    """Return [[bib_key, ...]] for papers sharing an identifier.

    Catches what `find_duplicate_titles` cannot: the same paper entered twice
    under titles too different to match. Two real examples from this repo, both
    of which were being emitted into the CV twice --

        arXiv 2407.13696  "Benchmark Agreement Testing Done Right: A Guide..."
                          "Do these LLM benchmarks agree? Fixing benchmark..."
        arXiv 2408.12259  "Can You Trust Your Metric? Automatic Concatenation"
                          "How Safe is Your Safety Metric? Automatic Conca..."

    An identifier is a much stronger claim than a title, so this is the reliable
    detector; titles are the fallback for papers with no identifier yet.
    """
    groups, seen = [], set()
    for _field, _value, keys in store.shared_identifiers():
        if keys_in_use is not None:
            keys = [k for k in keys if k in keys_in_use]
        if len(keys) < 2:
            continue
        signature = tuple(sorted(keys))
        if signature in seen:
            continue
        seen.add(signature)
        groups.append(list(signature))
    return groups


def duplicate_groups_by_bib_identifier(bib_text, keys_in_use=None):
    """Return [[bib_key, ...]] for bibliography entries sharing an identifier.

    Reads the bibliography instead of the identity store, and so does not depend
    on the store having been populated. The store learns an identifier only when a
    paper goes through resolution, which means an entry that arrived already
    complete -- carried over from DBLP, or pasted in by hand -- has no record at
    all, and `duplicate_groups_by_identifier` cannot see it however many
    identifiers the entry itself carries.

    Three papers were printed on the CV twice for exactly that reason, each with
    the same DOI written plainly in both of its entries:

        10.18653/v1/2023.conll-1.29   DBLP:conf/conll/KaridiCPA23 / karidi2023muler
        10.18653/v1/2022.conll-1.14   DBLP:conf/conll/PatelCA22   / patel2022neurons
        2022.coling-1.401             DBLP:conf/coling/YehudaiCFA22 / yehudai2022reinforcement

    Harvesting from the entries needs no accumulated state to be correct, so it
    keeps working on a fresh clone with no identity.json -- which is the case for
    every fork.
    """
    owners = {}
    for entry in parse_bibtex(bib_text):
        key = entry["item_name"]
        if keys_in_use is not None and key not in keys_in_use:
            continue
        for field, value in harvest_ids_from_bibtex(entry["content"]).items():
            slot = (field, normalize_identifier(field, value))
            if key not in owners.setdefault(slot, []):
                owners[slot].append(key)

    groups, seen = [], set()
    for slot in sorted(owners):
        signature = tuple(sorted(owners[slot]))
        if len(signature) < 2 or signature in seen:
            continue
        seen.add(signature)
        groups.append(list(signature))
    return groups


def merge_overlapping_groups(groups):
    """Collapse groups that share a member into one group.

    The detectors run independently and legitimately overlap: one pair can be
    caught by DOI, by arXiv id and by title at once. Left separate, each overlap
    becomes its own decision about the same paper, and two of them can disagree
    about which entry survives -- so the merge is done before anything is ranked,
    not after.
    """
    merged = []
    for group in groups:
        members = set(group)
        if len(members) < 2:
            continue
        overlapping = [m for m in merged if m & members]
        for m in overlapping:
            members |= m
            merged.remove(m)
        merged.append(members)
    return [sorted(m) for m in merged]


def duplicate_groups_by_any_known_title(name_by_key, bib_text):
    """Return [[bib_key, ...]] for papers sharing any title they are known under.

    A paper has two titles here -- the one in the table and the one in its BibTeX
    entry -- and they are not always the same string. When one entry was taken from
    Scholar and the other from DBLP, each source's idea of the title can end up
    filed against the other's row:

        slonim2021autonomous      table: An autonomous debating system
                                    bib: Project Debater - an autonomous debating system
        DBLP:...SlonimBABBBCCDE21 table: Project Debater  an Autonomous Debating System
                                    bib: An autonomous debating system

    One Nature paper, printed twice in the CV's Journals section. Comparing table
    titles to table titles finds nothing, because they differ by the "Project
    Debater" prefix; comparing bib titles to bib titles finds nothing either, for
    the same reason. Comparing every title of one paper against every title of the
    other is what makes the pair visible, and it is the crossing that carries the
    information -- each row is named what the other row's entry is titled.

    Nor could any identifier have caught it: `slonim2021autonomous` has no DOI, no
    eprint and no URL, so there was nothing to compare.

    Deliberately an equality test on normalized titles rather than a similarity
    one. Titles that differ only by a subtitle -- "Findings of the BabyLM
    Challenge" against "Findings of the Second BabyLM Challenge" -- are usually
    different papers, and a containment or fuzzy rule merges them.
    """
    titles_of = {}
    entries = {e["item_name"]: e for e in parse_bibtex(bib_text)}
    for key, name in name_by_key.items():
        titles = {normalize_title(str(name or ""))}
        entry = entries.get(key)
        if entry is not None:
            titles.add(normalize_title(extract_field(entry["content"], "title") or ""))
        titles_of[key] = {t for t in titles if t}

    owners = {}
    for key, titles in titles_of.items():
        for title in titles:
            owners.setdefault(title, []).append(key)

    groups, seen = [], set()
    for title in sorted(owners):
        signature = tuple(sorted(owners[title]))
        if len(signature) < 2 or signature in seen:
            continue
        seen.add(signature)
        groups.append(list(signature))
    return groups


def find_duplicate_titles(row_names):
    """Return {normalized_title: [raw names]} for table rows that collide.

    Two rows whose titles normalize identically are the same paper entered
    twice; the pipeline cannot tell which one to attach citations to.
    """
    groups = {}
    for name in row_names:
        name = str(name).strip()
        if not name:
            continue
        groups.setdefault(normalize_title(name), []).append(name)
    return {k: v for k, v in groups.items() if len(v) > 1}


_ARXIV_RE = re.compile(r'(?:arxiv[:/]|abs/)\s*(\d{4}\.\d{4,5})', re.IGNORECASE)
_DOI_RE = re.compile(r'\b(10\.\d{4,9}/[^\s{}",]+)', re.IGNORECASE)
#
# The terminator is a lookahead over the characters that actually end a URL in
# the place this is used. The previous version accepted only `.pdf`, `/` or
# end-of-string, and the sole caller is `harvest_ids_from_bibtex` -- where the URL
# is always inside a field and therefore always followed by `}`, `"` or `,`. So
# no ACL identifier was ever harvested from a bibliography, and two entries for
# one ACL paper had nothing in common to match on.
_ACL_RE = re.compile(r'aclanthology\.org/([A-Za-z0-9.\-]+?)(?:\.pdf)?(?=[/\s},"\']|$)',
                     re.IGNORECASE)


def normalize_identifier(field, value):
    """Fold an identifier to the form two sources can be compared in.

    DOIs and ACL ids are case-insensitive by specification, and the sources
    disagree in practice: DBLP writes `10.18653/V1/2023.CONLL-1.29` where the ACL
    Anthology writes the same DOI in lower case. Compared literally they are two
    identifiers, so the duplicate they prove goes unnoticed. The rest are left
    alone -- a DBLP key is case-sensitive, and Scholar's ids are opaque.
    """
    value = str(value or "").strip()
    if field in ("doi", "acl"):
        return value.lower()
    return value


def harvest_ids_from_bibtex(bibtex):
    """Pull whatever identifiers a BibTeX entry already carries."""
    ids = {}
    m = _ARXIV_RE.search(bibtex)
    if m:
        ids["arxiv"] = m.group(1)
    m = _DOI_RE.search(bibtex)
    if m:
        ids["doi"] = m.group(1).rstrip('.,')
    m = _ACL_RE.search(bibtex)
    if m:
        # rstrip as for the DOI: a trailing period belongs to the sentence.
        acl = m.group(1).rstrip('.,')
        if acl:
            ids["acl"] = acl
    return ids


def harvest_ids_from_s2(s2_data):
    """Map a Semantic Scholar `externalIds` payload onto our field names.

    This is the crosswalk: S2 returns ArXiv, DOI, ACL, DBLP and CorpusId for one
    paper in a single response, so binding any one of them binds them all.
    """
    if not s2_data:
        return {}
    ext = s2_data.get("externalIds") or {}
    mapping = {"ArXiv": "arxiv", "DOI": "doi", "ACL": "acl",
               "DBLP": "dblp", "CorpusId": "s2"}
    return {ours: str(ext[theirs]) for theirs, ours in mapping.items() if ext.get(theirs)}
